import { Currency, Wallet, Category } from '@/constants/types';

export const currencies: Currency[] = [
  { label: 'IDR', value: 'idr', flag: '🇮🇩' },
  { label: 'USD', value: 'usd', flag: '🇺🇸' },
];

const wallets: Wallet[] = [
  {
    category: 'Basic',
    total: 750000,
    accounts: [
      {
        id: 1,
        name: 'Cash',
        icon: 'Coins',
        color: '#FF5733',
        currency: 'usd',
        description: 'Recehan',
        balance: 250000,
        excludeFromReport: true,
      },
      {
        id: 2,
        name: 'BCA',
        icon: 'Landmark',
        color: '#33FF57',
        currency: 'idr',
        description: '',
        balance: 250000,
        excludeFromReport: false,
      },
      {
        id: 3,
        name: 'Jago',
        balance: 500000,
        icon: 'HandCoins',
        color: '#F235FF',
        currency: 'idr',
        description: '',
        excludeFromReport: false,
      },
      {
        id: 4,
        name: 'SuperBank',
        balance: 420000,
        icon: 'PiggyBank',
        color: '#FF33A1',
        currency: 'idr',
        description: '',
        excludeFromReport: false,
      },
    ],
  },
  {
    category: 'Saving',
    total: 250000,
    accounts: [
      {
        id: 5,
        name: 'Backup',
        icon: 'DatabaseBackup',
        color: '#A133FF',
        currency: 'idr',
        description: '',
        balance: 250000,
        excludeFromReport: false,
      },
      {
        id: 6,
        name: 'Cash',
        icon: 'Coins',
        color: '#FF5733',
        currency: 'idr',
        description: '',
        balance: 250000,
        excludeFromReport: false,
      },
      {
        id: 7,
        name: 'BCA',
        icon: 'Landmark',
        color: '#33FF57',
        currency: 'idr',
        description: '',
        balance: 250000,
        excludeFromReport: false,
      },
      {
        id: 8,
        name: 'Jago',
        balance: 500000,
        icon: 'HandCoins',
        color: '#F235FF',
        currency: 'idr',
        description: '',
        excludeFromReport: false,
      },
      {
        id: 9,
        name: 'SuperBank',
        balance: 420000,
        icon: 'PiggyBank',
        color: '#FF33A1',
        currency: 'idr',
        description: '',
        excludeFromReport: false,
      },
    ],
  },
  {
    category: 'Archived',
    total: 0,
    accounts: [
      {
        id: 10,
        name: 'Ovo',
        icon: 'Package',
        color: '#FFA133',
        currency: 'idr',
        description: '',
        balance: 250000,
        excludeFromReport: false,
      },
      {
        id: 11,
        name: 'Gopay',
        balance: 500000,
        icon: 'Package2',
        color: '#3357FF',
        currency: 'idr',
        description: '',
        excludeFromReport: false,
      },
      {
        id: 12,
        name: 'Cash',
        icon: 'Coins',
        color: '#FF5733',
        currency: 'idr',
        description: '',
        balance: 250000,
        excludeFromReport: false,
      },
      {
        id: 13,
        name: 'BCA',
        icon: 'Landmark',
        color: '#33FF57',
        currency: 'idr',
        description: '',
        balance: 250000,
        excludeFromReport: false,
      },
      {
        id: 14,
        name: 'Jago',
        balance: 500000,
        icon: 'HandCoins',
        color: '#F235FF',
        currency: 'idr',
        description: '',
        excludeFromReport: false,
      },
      {
        id: 15,
        name: 'SuperBank',
        balance: 420000,
        icon: 'PiggyBank',
        color: '#FF33A1',
        currency: 'idr',
        description: '',
        excludeFromReport: false,
      },
    ],
  },
];

const listExpense: Category[] = [
  {
    name: 'Food',
    icon: 'Medal',
    color: '#FF6347',
    children: [
      { name: 'Meals', icon: 'Newspaper', color: '#FF7F50' },
      { name: 'Snack & Drink', icon: 'PocketKnife', color: '#FFA07A' },
      { name: 'Restaurant', icon: 'BookUser', color: '#FF4500' },
    ],
  },
  {
    name: 'Transport',
    icon: 'Bus',
    color: '#FFD700',
    children: [
      { name: 'Gasoline', icon: 'Car', color: '#FFA500' },
      { name: 'Parking', icon: 'ParkingMeter', color: '#FF8C00' },
      { name: 'Taxi', icon: 'CarTaxiFront', color: '#FF6347' },
    ],
  },
  {
    name: 'Health',
    icon: 'Heart',
    color: '#98FB98',
    children: [
      { name: 'Medicine', icon: 'Piano', color: '#8FBC8F' },
      { name: 'Doctor', icon: 'Stethoscope', color: '#66CDAA' },
      { name: 'Insurance', icon: 'ShieldCheck', color: '#20B2AA' },
    ],
  },
  {
    name: 'Entertainment',
    icon: 'Gamepad',
    color: '#AFEEEE',
    children: [
      { name: 'Movies', icon: 'Film', color: '#48D1CC' },
      { name: 'Games', icon: 'Gamepad2', color: '#40E0D0' },
      { name: 'Music', icon: 'Music3', color: '#00CED1' },
    ],
  },
  {
    name: 'Utilities',
    icon: 'Lightbulb',
    color: '#6A5ACD',
    children: [
      { name: 'Electricity', icon: 'Bolt', color: '#7B68EE' },
      { name: 'Water', icon: 'Droplet', color: '#9370DB' },
      { name: 'Internet', icon: 'Wifi', color: '#8A2BE2' },
    ],
  },
  {
    name: 'Education',
    icon: 'Book',
    color: '#DA70D6',
    children: [],
  },
  {
    name: 'Shopping',
    icon: 'ShoppingCart',
    color: '#FF69B4',
    children: [
      { name: 'Clothes', icon: 'CircleDotDashed', color: '#FF1493' },
      { name: 'Electronics', icon: 'Laptop', color: '#C71585' },
      { name: 'Groceries', icon: 'ShoppingBag', color: '#DB7093' },
    ],
  },
];

const listIncome: Category[] = [
  {
    name: 'Salary',
    icon: 'Briefcase',
    color: '#4682B4',
    children: [],
  },
  {
    name: 'Investments',
    icon: 'ChartLine',
    color: '#4169E1',
    children: [
      { name: 'Stocks', icon: 'ChartBar', color: '#5F9EA0' },
      { name: 'Bonds', icon: 'ChartPie', color: '#6495ED' },
    ],
  },
  {
    name: 'Freelance',
    icon: 'FolderTree',
    color: '#B0E0E6',
    children: [],
  },
];

export { wallets, listExpense, listIncome };
